// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/affiliates/payouts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "List all affiliate payouts (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "page": {
                                    "type": "integer"
                                },
                                "page_size": {
                                    "type": "integer"
                                },
                                "payouts": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliatePayout"
                                    }
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/affiliates/payouts/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "Update a payout status (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payout ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payout status update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.updatePayoutStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "payout": {
                                    "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliatePayout"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/affiliates/program": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "Get the affiliate program configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "program": {
                                    "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliateProgram"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "Update the affiliate program configuration",
                "parameters": [
                    {
                        "description": "Program update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.updateProgramRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "program": {
                                    "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliateProgram"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/affiliate/links": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "List affiliate links for the current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "links": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliateLink"
                                    }
                                },
                                "page": {
                                    "type": "integer"
                                },
                                "page_size": {
                                    "type": "integer"
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "Create a new affiliate link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Link creation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.createLinkRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "link": {
                                    "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliateLink"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/affiliate/payout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "Request a payout for affiliate earnings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payout request payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http.requestPayoutRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "payout": {
                                    "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliatePayout"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/affiliate/referrals": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "List referrals for the current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "page": {
                                    "type": "integer"
                                },
                                "page_size": {
                                    "type": "integer"
                                },
                                "referrals": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.Referral"
                                    }
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/affiliate/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "Get affiliate statistics for the current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "link_count": {
                                    "type": "integer"
                                },
                                "total_clicks": {
                                    "type": "integer"
                                },
                                "total_conversions": {
                                    "type": "integer"
                                },
                                "total_earnings_cents": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/r/{code}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Affiliate"
                ],
                "summary": "Track a click on an affiliate link and redirect",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Affiliate link code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to target URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliateLink": {
            "type": "object",
            "properties": {
                "clickCount": {
                    "type": "integer",
                    "format": "int64"
                },
                "code": {
                    "type": "string"
                },
                "conversionCount": {
                    "type": "integer",
                    "format": "int64"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "targetURL": {
                    "type": "string"
                },
                "totalEarningsCents": {
                    "type": "integer",
                    "format": "int64"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliatePayout": {
            "type": "object",
            "properties": {
                "amountCents": {
                    "type": "integer",
                    "format": "int64"
                },
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "payoutMethod": {
                    "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.PayoutMethod"
                },
                "status": {
                    "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.PayoutStatus"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "github_com_southern-martin_ecommerce_services_affiliate_internal_domain.AffiliateProgram": {
            "type": "object",
            "properties": {
                "commissionRate": {
                    "type": "number",
                    "format": "float64"
                },
                "cookieDays": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "minPayoutCents": {
                    "type": "integer",
                    "format": "int64"
                },
                "referredBonusCents": {
                    "type": "integer",
                    "format": "int64"
                },
                "referrerBonusCents": {
                    "type": "integer",
                    "format": "int64"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_southern-martin_ecommerce_services_affiliate_internal_domain.PayoutMethod": {
            "type": "string",
            "enum": [
                "bank_transfer",
                "stripe"
            ],
            "x-enum-varnames": [
                "PayoutMethodBankTransfer",
                "PayoutMethodStripe"
            ]
        },
        "github_com_southern-martin_ecommerce_services_affiliate_internal_domain.PayoutStatus": {
            "type": "string",
            "enum": [
                "requested",
                "processing",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "PayoutStatusRequested",
                "PayoutStatusProcessing",
                "PayoutStatusCompleted",
                "PayoutStatusFailed"
            ]
        },
        "github_com_southern-martin_ecommerce_services_affiliate_internal_domain.Referral": {
            "type": "object",
            "properties": {
                "commissionCents": {
                    "type": "integer",
                    "format": "int64"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderID": {
                    "type": "string"
                },
                "orderTotalCents": {
                    "type": "integer",
                    "format": "int64"
                },
                "referredID": {
                    "type": "string"
                },
                "referrerID": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_southern-martin_ecommerce_services_affiliate_internal_domain.ReferralStatus"
                }
            }
        },
        "github_com_southern-martin_ecommerce_services_affiliate_internal_domain.ReferralStatus": {
            "type": "string",
            "enum": [
                "pending",
                "confirmed",
                "paid"
            ],
            "x-enum-varnames": [
                "ReferralStatusPending",
                "ReferralStatusConfirmed",
                "ReferralStatusPaid"
            ]
        },
        "internal_adapter_http.createLinkRequest": {
            "type": "object",
            "required": [
                "target_url"
            ],
            "properties": {
                "target_url": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_http.requestPayoutRequest": {
            "type": "object",
            "required": [
                "amount_cents",
                "payout_method"
            ],
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "payout_method": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_http.updatePayoutStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_http.updateProgramRequest": {
            "type": "object",
            "properties": {
                "commission_rate": {
                    "type": "number"
                },
                "cookie_days": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "min_payout_cents": {
                    "type": "integer"
                },
                "referred_bonus_cents": {
                    "type": "integer"
                },
                "referrer_bonus_cents": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer token (via Kong gateway)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:28097",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Affiliate Service API",
	Description:      "Affiliate link tracking, referral management, and payout processing.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
